server:
  port: 8081

elasticsearch:
  host: 127.0.0.1
  port: 9200

datasource:
  url: 127.0.0.1:3306

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${datasource.url}/test_es
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1800000

# mybatis 配置
mybatis:
  type-aliases-package: com.ymtxb.esbase.entity # 指定别名entity包
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名规范，数据库表字段user_id自动匹配到实体类  userId 字段

